//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posting
    {
        public int ID { get; set; }
        public int TransactionID { get; set; }
        public int AccountID { get; set; }
        public int JournalID { get; set; }
        public int AccountingPeriodID { get; set; }
        public int AssetTypeID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AccountingPeriod AccountingPeriod { get; set; }
        public virtual AssetType AssetType { get; set; }
        public virtual Journal Journal { get; set; }
    }
}
